name: customize
description: Customize is awesome Flutter package to create beautiful UI.
version: 0.2.0
homepage: "https://github.com/Aniketkhote/customize"
documentation: https://aniketkhote.github.io/customize-docs/#/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter: null
